[2025-01-09T18:59:17.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-09T18:59:17.203+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_clickhouse_test.spark_submit_task manual__2025-01-09T18:39:45.456197+00:00 [queued]>
[2025-01-09T18:59:17.225+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_clickhouse_test.spark_submit_task manual__2025-01-09T18:39:45.456197+00:00 [queued]>
[2025-01-09T18:59:17.226+0000] {taskinstance.py:2866} INFO - Starting attempt 6 of 6
[2025-01-09T18:59:17.264+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2025-01-09 18:39:45.456197+00:00
[2025-01-09T18:59:17.282+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=707) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-09T18:59:17.290+0000] {standard_task_runner.py:72} INFO - Started process 716 to run task
[2025-01-09T18:59:17.285+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_clickhouse_test', 'spark_submit_task', 'manual__2025-01-09T18:39:45.456197+00:00', '--job-id', '1178', '--raw', '--subdir', 'DAGS_FOLDER/spark_clickhouse_test.py', '--cfg-path', '/tmp/tmppc8zoh1d']
[2025-01-09T18:59:17.297+0000] {standard_task_runner.py:105} INFO - Job 1178: Subtask spark_submit_task
[2025-01-09T18:59:17.409+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_clickhouse_test.spark_submit_task manual__2025-01-09T18:39:45.456197+00:00 [running]> on host 6d6490d8a5cc
[2025-01-09T18:59:17.624+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rvegrc' AIRFLOW_CTX_DAG_ID='spark_clickhouse_test' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T18:39:45.456197+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-09T18:39:45.456197+00:00'
[2025-01-09T18:59:17.627+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-09T18:59:17.650+0000] {spark_submit.py:304} INFO - Could not load connection string spark, defaulting to yarn
[2025-01-09T18:59:17.656+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --packages com.clickhouse.spark:clickhouse-spark-runtime-3.5_2.12:0.8.0,com.clickhouse:clickhouse-jdbc:0.7.1-patch1,com.clickhouse:clickhouse-http-client:0.7.1-patch1,org.apache.httpcomponents.client5:httpclient5:5.3.1 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 5g --driver-memory 5g --name arrow-spark --verbose dags/spark_app/spark_1.py
[2025-01-09T18:59:21.856+0000] {spark_submit.py:634} INFO - Using properties file: null
[2025-01-09T18:59:22.309+0000] {spark_submit.py:634} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-01-09T18:59:22.311+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-01-09T18:59:22.313+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-01-09T18:59:22.315+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-01-09T18:59:22.316+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-01-09T18:59:22.319+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-01-09T18:59:22.322+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-01-09T18:59:22.324+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-01-09T18:59:22.327+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-01-09T18:59:22.329+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-01-09T18:59:22.331+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-01-09T18:59:22.387+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages com.clickhouse.spark:clickhouse-spark-runtime-3.5_2.12:0.8.0,com.clickhouse:clickhouse-jdbc:0.7.1-patch1,com.clickhouse:clickhouse-http-client:0.7.1-patch1,org.apache.httpcomponents.client5:httpclient5:5.3.1 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 5g --driver-memory 5g --name arrow-spark --verbose dags/spark_app/spark_1.py. Error code is: 1.
[2025-01-09T18:59:22.403+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spark_clickhouse_test, task_id=spark_submit_task, run_id=manual__2025-01-09T18:39:45.456197+00:00, execution_date=20250109T183945, start_date=20250109T185917, end_date=20250109T185922
[2025-01-09T18:59:22.459+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-09T18:59:22.463+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1178 for task spark_submit_task (Cannot execute: spark-submit --master yarn --packages com.clickhouse.spark:clickhouse-spark-runtime-3.5_2.12:0.8.0,com.clickhouse:clickhouse-jdbc:0.7.1-patch1,com.clickhouse:clickhouse-http-client:0.7.1-patch1,org.apache.httpcomponents.client5:httpclient5:5.3.1 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 5g --driver-memory 5g --name arrow-spark --verbose dags/spark_app/spark_1.py. Error code is: 1.; 716)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages com.clickhouse.spark:clickhouse-spark-runtime-3.5_2.12:0.8.0,com.clickhouse:clickhouse-jdbc:0.7.1-patch1,com.clickhouse:clickhouse-http-client:0.7.1-patch1,org.apache.httpcomponents.client5:httpclient5:5.3.1 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 5g --driver-memory 5g --name arrow-spark --verbose dags/spark_app/spark_1.py. Error code is: 1.
[2025-01-09T18:59:22.531+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-09T18:59:22.575+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-09T18:59:22.586+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
